In [106]:
import numpy as np
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans


data = np.genfromtxt ('iris.csv', delimiter=",")
print (data)



[[1.00e+00 5.10e+00 3.50e+00 1.40e+00 2.00e-01 0.00e+00]
 [2.00e+00 4.90e+00 3.00e+00 1.40e+00 2.00e-01 0.00e+00]
 [3.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01 0.00e+00]
 [4.00e+00 4.60e+00 3.10e+00 1.50e+00 2.00e-01 0.00e+00]
 [5.00e+00 5.00e+00 3.60e+00 1.40e+00 2.00e-01 0.00e+00]
 [6.00e+00 5.40e+00 3.90e+00 1.70e+00 4.00e-01 0.00e+00]
 [7.00e+00 4.60e+00 3.40e+00 1.40e+00 3.00e-01 0.00e+00]
 [8.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01 0.00e+00]
 [9.00e+00 4.40e+00 2.90e+00 1.40e+00 2.00e-01 0.00e+00]
 [1.00e+01 4.90e+00 3.10e+00 1.50e+00 1.00e-01 0.00e+00]
 [1.10e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01 0.00e+00]
 [1.20e+01 4.80e+00 3.40e+00 1.60e+00 2.00e-01 0.00e+00]
 [1.30e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01 0.00e+00]
 [1.40e+01 4.30e+00 3.00e+00 1.10e+00 1.00e-01 0.00e+00]
 [1.50e+01 5.80e+00 4.00e+00 1.20e+00 2.00e-01 0.00e+00]
 [1.60e+01 5.70e+00 4.40e+00 1.50e+00 4.00e-01 0.00e+00]
 [1.70e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01 0.00e+00]
 [1.80e+01 5.10e+00 3.50e+00 1.

In [107]:
x = data[:, 1 : 5]
print (x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [108]:
kmean = KMeans(n_clusters = 3).fit(x)
kmean.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1])

In [109]:
kmean.predict(x)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1])

In [110]:
kmean.cluster_centers_

array([[5.006     , 3.418     , 1.464     , 0.244     ],
       [5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [111]:
def tf_reset():
    try:
        sess.close()
    except:
        pass
    tf.reset_default_graph()
    return tf.Session()

In [123]:
sess = tf_reset()
input_ph = tf.placeholder(dtype=tf.float32, shape=[None, 4])

In [124]:
y = data[:,5]
print(y)
output_ph = tf.one_hot(indices = y,depth = 3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2.]


In [125]:
W0 = tf.get_variable(name='w0',shape=[4,8],initializer=tf.initializers.random_normal())
W1 = tf.get_variable(name='w1',shape=[8,4],initializer=tf.initializers.random_normal())
W2 = tf.get_variable(name='w2',shape=[4,3],initializer=tf.initializers.random_normal())

weights = [W0,W1,W2]
activation = [tf.sigmoid,tf.sigmoid,None]

layer = input_ph
for W, activation in zip(weights, activation):
        layer = tf.matmul(layer, W)
        if activation is not None:
            layer = activation(layer)
            
output_pred = layer
sess.run(tf.global_variables_initializer())

mse = tf.reduce_mean(0.5 * tf.square(output_pred - output_ph))
opt = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(mse)
for i in range(3000):
    _,loss = sess.run([opt,mse],feed_dict={input_ph : x})

In [126]:
pred = sess.run(output_pred,feed_dict={input_ph:x})
pred = np.argmax(pred,1)
np.mean(pred == y) 

0.96